modLoader="javafml"
loaderVersion="[${fmlVersion},)"
license="LGPL v2.1"
issueTrackerURL="https://github.com/BiggerSeries/BiggerReactors/issues/"

[[mods]] 
modId="biggerreactors" 
version="${version}" 
displayName="Bigger Reactors" 
displayURL="https://biggerseries.net/" 
logoFile="BiggerReactors.png" 
credits="ErogeneousBeef for the original Big Reactors mod, that this is spiritually (and semi-literally) derived from"
authors="RogueLogix, gizmocodes, Ridanisaurus" 
description='''
Big Reactors, but even bigger

Part of the BiggerSeries of mods

Official continuation of Big Reactors
'''

[[dependencies.biggerreactors]] 
    modId="forge" 
    mandatory=true 
    versionRange="[${forgeVersion},)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.biggerreactors]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcVersion}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.biggerreactors]]
    modId="phosphophyllite"
    mandatory=true
    versionRange="${phosVersionRange}"
    ordering="NONE"
    side="BOTH"

