modLoader="javafml"
loaderVersion="[${loader_version},)"
license="LGPL v2.1"
issueTrackerURL="https://github.com/BiggerSeries/BiggerReactors/issues/"

[[mods]] 
modId="biggerreactors" 
version="${version}" 
displayName="Bigger Reactors" 
displayURL="https://biggerseries.net/" 
logoFile="biggerreactors.png"
credits="ErogeneousBeef for the original Big Reactors mod, that this is spiritually (and semi-literally) derived from"
authors="RogueLogix, gizmocodes, Ridanisaurus" 
description='''
Big Reactors, but even bigger

Part of the BiggerSeries of mods

Official continuation of Big Reactors
'''

[[dependencies.biggerreactors]] 
    modId="neoforge"
    required=true
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.biggerreactors]]
    modId="minecraft"
    required=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.biggerreactors]]
    modId="phosphophyllite"
    required=true
    versionRange="${phos_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.biggerreactors]]
    modId="quartz"
    required=true
    versionRange="${quartz_version_range}"
    ordering="NONE"
    side="BOTH"

